### ISSUE TITLE
Itemprop incorrect

### ISSUE THREAD

**Issue by ColonelBlimp** [WeaverStever/BlogSpot-Metadata-Template#1]
<div itemprop='image' itemscope='itemscope' itemtype='https://schema.org/ImageObject'>
      <b:if cond='data:post.firstImageUrl'>
        <img style='display:none;' expr:src='data:post.firstImageUrl' alt='Textual description of firstImageUrl'/>
       
           <meta itemprop='url' expr:content='data:post.firstImageUrl'/> 
      </b:if>
      <meta itemprop='width' content='800'/> 
      <meta itemprop='height' content='800'/>
    </div>

**Comment by serkanince** [comment]
It has to be like this

`    <div itemprop='image' itemscope='itemscope' itemtype='https://schema.org/ImageObject'>
      <b:if cond='data:post.firstImageUrl'>
        <img style='display:none;' expr:src='data:post.firstImageUrl' alt='Textual description of firstImageUrl'/>
        <meta itemprop='image' expr:content='data:post.firstImageUrl'/>
      </b:if>
      <meta itemprop='width' content='800'/> 
      <meta itemprop='height' content='800'/>
      **<meta itemprop='url' expr:content='data:post.firstImageUrl' />**
    </div>`

**Comment by WeaverStever** [comment]
@ColonelBlimp 

We may be both wrong on this one, according to Example 1 on http://schema.org/ImageObject, the URL itemprop for an ImageObject would be itemprop='contentUrl'

**Comment by WeaverStever** [comment]
@ColonelBlimp
I did some testing, Google SDTT is expecting itemprop='url'

Thank you!
